
inhibit_all_warnings!
use_frameworks!

workspace 'BLEScanner.xcworkspace'

def shared_pods
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
end

# Common modules

target 'Core' do
  project 'Common/Core/Core'
  shared_pods
end

# Feature modules

target 'BLEScanner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BLEScanner

  target 'BLEScannerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
