
inhibit_all_warnings!
use_frameworks!

workspace 'BLEScanner.xcworkspace'

def shared_pods
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
end

# Common modules

target 'Core' do
  project 'Common/Core/Core'
  shared_pods
end

target 'BlueKit' do
  project 'Common/BlueKit/BlueKit'
  shared_pods
end

# Feature modules

target 'Peripherals' do
  project 'Features/Peripherals/Peripherals'
  shared_pods
  
  target 'PeripheralsTests' do
    pod 'RxTest'
    shared_pods
  end
end

target 'PeripheralDetails' do
  project 'Features/PeripheralDetails/PeripheralDetails'
  shared_pods
  
  target 'PeripheralDetailsTests' do
    pod 'RxTest'
    shared_pods
  end
end

target 'BLEScanner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BLEScanner
  shared_pods

  target 'BLEScannerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
